### ISSUE TITLE
[README Names] - New branch names - What should they be?

### ISSUE THREAD

**Issue by uo277915** [Arquisoft/dede_en2a#1]
Hey guys,
I was thinking on how to name the branch, Ithough of something like <name>Name. In my case AndresName...
What do you think? :)

**Comment by LorenzoLaRocca** [comment]
Seems a good idea for now, I am going to rename my branch using that format

**Comment by uo277915** [comment]
Thanks guys! I think we can all agree on the name:

<name>Name
