### ISSUE TITLE
[DATABASE] Database to be used

### ISSUE THREAD

**Issue by uo271580** [Arquisoft/dede_en2a#11]
Let's do some research for the database that we are going to use

**Comment by uo271580** [comment]
I made some research on the Database to use. I found good information at  https://www.hyperlinkinfosystem.com/blog/top-10-databases-for-react-native-app-development and https://www.business2community.com/tech-gadgets/top-5-databases-for-react-native-app-development-02383205. 

The best choose for me are Firebase, PouchDB or MongoDB.

As the lecture teacher mentions a lot MongoDB i would say it is the best choice

**Comment by angelip2303** [comment]
I don't think we really need a SQL DB as I don't really think the data is highly structured and relationships between data are not as important. So, considering we are not having an structured model, NoSQL DBs tend to be faster and simpler. All in all, I would go for a document database:

* With MongoDB (or any other alternative) we can store several key-value pairs in JSON format. It's easy to use with JS in the backend and I have found an integration for Java, depending on the language we choose for the server-side of the application.

Some interesting sites:
https://www.red-gate.com/simple-talk/databases/nosql/how-to-choose-between-sql-and-nosql-databases/
https://www.mongodb.com/nosql-explained/nosql-vs-sql
https://www.mongodb.com/nosql-explained

**Comment by uo271580** [comment]
Okay, we have decided to use MongoDB
