### ISSUE TITLE
Problem when deployment

### ISSUE THREAD

**Issue by uo277776** [Arquisoft/dede_en2a#126]
Hi Pablo, I was trying to deploy the app, but when I create a new release it fails in the e2e test. I have commented all the test but it continue failing in npm --prefix webapp run build, it says that it can't compile. 

I tried to execute this command in my computer and works well, so I don't know the reason of the problem.

If you can take a look and revise if there is something wrong in the docker or actions file.

**Comment by pglez82** [comment]
Just comment the full e2e job in the actions yml file. Remember to update the dependencies between jobs. Next day we will work on these tests so we can incorporate this again.

**Comment by uo277776** [comment]
Okey, I'm going to try it now. Thank you

**Comment by uo277776** [comment]
Now it works but it deploys the initial app because we are using the docker-compose-deploy file that uses the inital images, so in order to deploy our application we should modified this line in actions yml file.

wget https://raw.githubusercontent.com/pglez82/asw2122_0/master/docker-compose-deploy.yml -O docker-compose.yml

We should replace this with our docker-compose.yml file, is that correct?

**Comment by pglez82** [comment]
No, you should create your own docker-compose-deploy.yml in your repository pointing to your docker images in the github registry. Then, update the link in the wget ...

**Comment by uo277776** [comment]
I have a problem when the actions have to get the image from the registry.  I don't know what is happening because I think the deploy file is pointing correctly to the images.

Sorry for the incovinience, but I want to have the application deploy as soon as posible so as not to have problems in the delivery.

**Comment by pglez82** [comment]
Yes, the problem is that your packages are private. 

![image](https://user-images.githubusercontent.com/10683040/159971355-c5157641-e17f-43d9-9a6a-cd6339bc8fb2.png)

You can change that, clicking on the image in Packages and going to package settings. In the danger zone, put them to public (both). Next releases will be public by default (though I am not completely sure, you can confirm it to me when you test it)

After this change, it should work.

**Comment by uo277776** [comment]
I don't know why, but I'm not able to find any packages, neither private nor public. I think that the action is not pushing the image, hovewer the workflow goes green.

**Comment by pglez82** [comment]
https://github.com/orgs/Arquisoft/packages?repo_name=dede_en2a

Packages are here.

**Comment by uo277776** [comment]
Maybe is only my problem, but I can't see any package there.

![package](https://user-images.githubusercontent.com/90835490/159981773-91701003-508f-4d10-a36c-2c415d6cf4c7.jpg)

**Comment by pglez82** [comment]
I changed both packages to public. Let me know if you can see them now.

**Comment by uo277776** [comment]
Yes, now I can see the packages. Thamk you, I will try if it works.

**Comment by uo277776** [comment]
It is deploying well. Now I have to manage some enviroment variables to connect with the rest api, but the frontend part of the app works and it is deploy. Thank you.
