### ISSUE TITLE
Use .env file with jest

### ISSUE THREAD

**Issue by uo271580** [Arquisoft/dede_en2a#158]
I am trying to use the .env variables on the tests but it seems that it doesn't get them. I look some options on internet but none of them worked for me. Do you know how to do it

**Comment by uo271580** [comment]
The things i tried where

Add  setupFiles: [
        'dotenv/config'
    ], in the jest.config

and

Add jest--setupFiles dotenv/config on the package.json where the script is defined

**Comment by pglez82** [comment]
what tests are you trying to execute? Unitary?

**Comment by pglez82** [comment]
why is this closed? What was the problem/solution?

**Comment by uo271580** [comment]
I found a solution now, adding
setupFilesAfterEnv: ["<rootDir>/tests/env.js"], to the jest.config and assigning in that files the env variables
