### ISSUE TITLE
[WIKI] Format for the Architectural Decision Records 

### ISSUE THREAD

**Issue by uo277915** [Arquisoft/dede_en2a#17]
Hey guys @Arquisoft/team-dede_en2a-students ! I was just finishing the Meeting Minutes from the [Meeting 07 02 2022](https://github.com/Arquisoft/dede_en2a/wiki/Meeting-07-02-2022) and I found that we didn't really decide how will we do the Architectural Decision Records! 

After reading the documentation given on the pdf slides I looked a little deeper and I found [this Template](https://github.com/joelparkerhenderson/architecture-decision-record/blob/main/templates/decision-record-template-by-michael-nygard/index.md) that I think we could use.

I also found [this video](https://youtu.be/LMBqGPLvonU?t=70) that seems interesting enough that explains what should be included in each part.

I thus created [a Template](https://github.com/Arquisoft/dede_en2a/wiki/ADR-%230%3A-Template), which is a version of the one I linked earlier, in the wiki so we can just duplicate it and modify It however we need. 

For now I'm creating new Pages in the wiki with the ADRs and linking them in the minutes.

What do you think?

**Comment by uo277776** [comment]
I think it's a very good decision because this way we can see the important architectural decisions without having to enter each meeting.

Good job!

**Comment by noeliaigc** [comment]
I agree with Alvaro, I find it a good idea!!! 👍

**Comment by LorenzoLaRocca** [comment]
The template is easy to understand and yes it will help us a lot when a team member can't join a meeting. Nice work!
