### ISSUE TITLE
[WIKI] Meeting 07 02 2022 ready for revision 

### ISSUE THREAD

**Issue by uo277915** [Arquisoft/dede_en2a#18]
Hey @Arquisoft/team-dede_en2a-students!
I've finished writing the [Minutes](https://github.com/Arquisoft/dede_en2a/wiki/Meeting-07-02-2022) for the last reunion, whenever you have time please check it out and share your opinion!
Also check #17 whenever you can.

**Comment by LorenzoLaRocca** [comment]
Hey! I checked the [Minutes](wiki/Meeting07022022) and seems good to me. Just maybe can it make sense if we add the place of the meeting or if it was face to face or online?
