### ISSUE TITLE
UseState for Reviews

### ISSUE THREAD

**Issue by uo277776** [Arquisoft/dede_en2a#201]
We should modify the review system to avoid reloading the page when a new review is added.
Also check the review is not empty before creating it

**Comment by angelip2303** [comment]
I have noticed another bug regarding this feature: you have to click twice in order to open the CreateRating dialog. That should also be fixed. I will take a look at it!

**Comment by uo271580** [comment]
I fixed the use state so it doesnt have to reload for now
