### ISSUE TITLE
Quality gate not computed

### ISSUE THREAD

**Issue by uo277776** [Arquisoft/dede_en2a#250]
Hi Pablo! As you say in class yesterday, the quality gate was not computing because firts we have to set up the gate.
If you can take a look and try to fix this problem as soon as posible to have it ready for the final presentation. Thanks!

**Comment by pglez82** [comment]
I was checking it yesterday. It seems that anything went into master for three weeks. In the website says that the quality gate should be computed in the next run. I was checking and your configuration is identical to the other teams as there is a default quality gate that doesn't need to be configured. Are you planing to merge something into master soon to see if the quality gate is computed?

**Comment by uo271580** [comment]
Yes, we are doing some changes today and planning to merge them to master and also deploying the app, so we'll see if the quality gate is computed then

**Comment by uo277776** [comment]
Now, the quality gate is computed, although is failing but we have to check the errors.
