### ISSUE TITLE
Problem with private packages

### ISSUE THREAD

**Issue by uo277776** [Arquisoft/dede_en2a#254]
Hi! We add a new docker image for the carriers api that we created. So, when we try to deploy the app, an error happens because that package is private. This problem also happen to us with the webapp and the restapi packages. 

So if you could change the visibility of the package to public, would be great. The package name is carriersapi.

Thanks!

**Comment by pglez82** [comment]
Done!

**Comment by uo277776** [comment]
Thanks!
