### ISSUE TITLE
SonarCloud Quaility Gate

### ISSUE THREAD

**Issue by uo271580** [Arquisoft/dede_en2a#256]
Pablo, we have checked the sonar cloud and we still have 3 security hotspots that are told to change. We have reviewed them and there is not much we can do about them. We can tell SonarCloud that they are already revised but we don't have rights to do so. 

It is possible to you to give us rights or tell SonarCloud those hotspots are revised?

**Comment by pglez82** [comment]
I have added some permissions. Let me know if that works. I do not have experience with sonarcloud so maybe we need some trial and error here.

**Comment by uo271580** [comment]
It let me do it, thank you
