### ISSUE TITLE
e2e tests

### ISSUE THREAD

**Issue by uo271580** [Arquisoft/dede_en2a#258]
When trying to run the test:e2e command it says that the jest command is not recognizable. How can we do it on a windows ps?

Also "test:e2e": "start-server-and-test 'npm --prefix ../restapi start' http://localhost:5000/ prod 3000 'cd e2e && jest'", with this test:e2e script the response is 404 as no especific route is written, but we may use different ones, so what should we do?

**Comment by pglez82** [comment]
This is how you do it on windows (also works in linux):
https://github.com/Arquisoft/dede_en3a/issues/139#issuecomment-1107533169

About the second part of the question, I do not understand it. The urls that are in the command is for the library start-server-and-test to know when the services are ready so tests can be started.

**Comment by uo271580** [comment]
How can we start the restapi and webapp both at the same time? Because with the solution above only the webapp is started

**Comment by pglez82** [comment]
"test:e2e": "start-server-and-test 'npm --prefix ../restapi start' http://localhost:5000/ prod 3000 'jest --rootDir=e2e --config=./e2e/jest.config.ts'"

**Comment by uo271580** [comment]
If we run that commando, when trying to access localhost:5000 the webapp returns a 404 since we do not have that route.
If we put localhost:5000/products the shop is shown, but will it work if we want to access localhost:5000/orders?

**Comment by uo271580** [comment]
And also, how can we make the browser stop more time when doing the e2e tests?

**Comment by pglez82** [comment]
You need to change the url http://localhost:5000/ with something that exists in your rest api. This second parameter just tells the command that when the url replies, the service is ready and he can launch the tests. The same for prod 3000. prod is the command to execute, 3000 is the url to check (by default, if we only give a port it puts localhost before).

**Comment by pglez82** [comment]
> And also, how can we make the browser stop more time when doing the e2e tests?

Check the documentation: https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagewaitfornavigationoptions

First thing is to increment jest time out (in the jest-config of e2e tests). Then you can use waitFor functions to wait for navigation, or wait for elements to appear in the screen.

**Comment by uo271580** [comment]
I am trying to get a button from the home page (is inside another element) but i can not get it using the page element, and i tried many different things without success. How can i get a button inside another element and click it with puppeteer (code is on e2etest branch)

**Comment by pglez82** [comment]
what button? can you tell me at least the text of the button? I need to try it. Maybe I am asking to much and there is only one button in the home page :)

**Comment by uo271580** [comment]
The button with Start shopping text

**Comment by pglez82** [comment]
Element is not a button is a link (<a>). So the code will work:
```javascript
await expect(page).toClick('a', { text: 'Start shopping' })
```
With that the test passes at least in my computer.

**Comment by uo271580** [comment]
Thank you
