### ISSUE TITLE
Problem with acceptance tests when deploying

### ISSUE THREAD

**Issue by uo277776** [Arquisoft/dede_en2a#279]
Hi Pablo. We try to add the e2e tests to the CI system. Hovewer, there has been a problem when compiling it. It says that the CI system treats warnings as errors, because proccess.env.CI = true. I have been doing some research about this but I couldn't find anything. 

We are not too worried about this, because we can deploy the application anyway, but it would be nice to have it perfect.

Also the acceptance tests are working correctly in my own computer.

**Comment by uo277776** [comment]
Yes, that worked. Now it is running the e2e tests. Let's see if the whole job works.

**Comment by uo277776** [comment]
The tests have failed because the enviroment variables for the restapi and the webapp has not been declared, but I guess it will be the same as the CI variable.

**Comment by uo277776** [comment]
Okey, I add the enviroment variables and it work perfect, and the CI process deploy correctly. Thank you so much!

**Comment by pglez82** [comment]
Great!
