### ISSUE TITLE
[WIKI] Meeting 14 02 2022 ready for revision

### ISSUE THREAD

**Issue by angelip2303** [Arquisoft/dede_en2a#32]
I have finished writing today's [meeting](https://github.com/Arquisoft/dede_en2a/wiki/Meeting-14-02-2022/). You can check it whenever you can so you may share some improvements than I can fix.

**Comment by uo277776** [comment]
I just checked it and in my opinion it is perfect and there is no need no add anything else.

Very good work Angel!

**Comment by uo277915** [comment]
I have just double checked it and the minutes are very good! Nice Job @angelip2303! 🕺🕺
