### ISSUE TITLE
[Diagrams Tool] What do we choose?

### ISSUE THREAD

**Issue by LorenzoLaRocca** [Arquisoft/dede_en2a#37]
Hey guys, I wanted to add some tool in the Development Tools table to create diagrams. Do you have any familiarity with already or whataver you want to advise to use? 
The Teacher on the page linked Visual Paradigms I don't know if you want to use that or another. 
See you!

**Comment by noeliaigc** [comment]
Hi! For doing the section 5 of documentation I have to use a graphic tool for the diagrams and I used "UMLet" it is mentioned in the lab slides. I found it easy to work with it and the result was good.

**Comment by uo277776** [comment]
In my case, for doing section 3.1 I used the tool PlantUML, that you write the code directly in the adoc file. It is also easy to use once you understand how it works. The disadvatange is that in order to see the diagram to have to build the html file.

**Comment by LorenzoLaRocca** [comment]
hey! since you used 2 different tools I am gonna put both of them for the Doc 0.1. We will discuss about them in the next meetings. So I am not closing yet this issue.  Have a nice weekend guys!
