### ISSUE TITLE
Meeting 21 02 2022

### ISSUE THREAD

**Issue by noeliaigc** [Arquisoft/dede_en2a#53]
Hi! I was just doing the meeting for todays lab and I was wondering if in the section about "Work assignment" should I write that we have to fix some documentation sections and when we have the other reunion this week update with what we decide or if other person is going to do a new page in the minutes of what we decide in that meeting.
Another issue that I have seen is that in the [ADR #1](https://github.com/Arquisoft/dede_en2a/wiki/ADR-%231%3A-Backend-Programming-Language) and the [ADR #4](https://github.com/Arquisoft/dede_en2a/wiki/ADR-%234%3A-Backend-Programming-Language) two different backend languages are proposed. I suppose that the good one is the [ADR #4](https://github.com/Arquisoft/dede_en2a/wiki/ADR-%234%3A-Backend-Programming-Language) so, should be the [ADR #1](https://github.com/Arquisoft/dede_en2a/wiki/ADR-%231%3A-Backend-Programming-Language) deleted?

**Comment by uo277776** [comment]
Hi, I think that each reunion should be in a diferrent page in the minutes, so we should write the minutes also for that metting,

About the ADR, it sounds to me that in theory clasess the teacher said that the previous ADR should not be deleted, because that way we could see the changes in the decisions.

**Comment by noeliaigc** [comment]
I finished writing the [Minutes](https://github.com/Arquisoft/dede_en2a/wiki/Meeting-21-02-2022).
Please let me know if I missed or if there is anything to improve.

**Comment by angelip2303** [comment]
I think everything is just fine!
