### ISSUE TITLE
Small prototype version

### ISSUE THREAD

**Issue by uo277776** [Arquisoft/dede_en2a#54]
Hello! I've working with Pablo these days in a small prototype of the application. It is very simple, you can only see the products and add them to the shopping cart, but it is a base to understand how it works and start doing a better approach. 

You can take a look to this code in the tests branch and you can deployed it in your computer to see the results. 

If there is something you don't understand, do not hesitate to ask me!

**Comment by uo277915** [comment]
Wow guys, great job! That's really cool.

I've been working on some prototypes of how the pages might look at the end with the CSS and everything, I'll show it to you on the next meeting and then when we all approve it ill upload them to an issue. ^^
