### ISSUE TITLE
[REVIEWS] - Formatting the messages 

### ISSUE THREAD

**Issue by angelip2303** [Arquisoft/dede_en2a#6]
Maybe it could be a nice idea to add some tags before our commit/pr messages; i.e: [TAG] _commit message_.

Do you think its a nice idea?

**Comment by uo277915** [comment]
Seems like a cool idea! I added "[REVIEWED]" on the commit message after I checked some pull requests. I think it looks clearer to read and know what it is! Gread idea! 😎
