### ISSUE TITLE
Meeting 28 02 2022 ready for revision

### ISSUE THREAD

**Issue by uo277776** [Arquisoft/dede_en2a#74]
I have just finished writing the notes for the last [meeting](https://github.com/Arquisoft/dede_en2a/wiki/Meeting-28-02-2022).
It would be great if you can look at it and tell me if you think I can improve anything!

Also I wrote the [decision record](https://github.com/Arquisoft/dede_en2a/wiki/ADR-%239%3A-Code-formatter) for the code formatter.

**Comment by angelip2303** [comment]
Good Job, I think everything is fine!
